### ISSUE TITLE
Assumption in package about IApplication builder namespace

### ISSUE THREAD

**Issue by DanHarman** [PrometheusClientNet/Prometheus.Client.Owin#2]
Hi,

I've got an aspnetcore 2.0 project targeting net462. This means my `IApplicationBuilder` comes from `Microsoft.AspNetCore.Builder` however there is a `#if` in the `PrometheusExtensions.cs` which unfortunately assumes it is coming from `Owin`:

```
#if NETSTANDARD
using Microsoft.AspNetCore.Builder;
#else
using Owin;
#endif
```

I suspect these should actually be two separate packages to resolve this as Owin is not really the same as AspNetCore these days...

**Comment by phnx47** [comment]
I was already thinking about splitting the package. Thank you!

**Comment by DanHarman** [comment]
No thank you for a superior fork!

**Comment by phnx47** [comment]
I created issue: https://github.com/phnx47/Prometheus.Client.Owin/issues/4
