### ISSUE TITLE
Update Prometheus.Client library

### ISSUE THREAD

**Issue by gavindew** [PrometheusClientNet/Prometheus.Client.Owin#5]
Prometheus.Client was just upgraded to v2.0.. Can you update Prometheus.Client.Owin so we can use this. It fixes a critical issue with the case of the metric type introduced with Prometheus 2.4

**Comment by phnx47** [comment]
Yes, of course. On this weekend

**Comment by phnx47** [comment]
I apologize for the delay

**Comment by phnx47** [comment]
@gavindew  Released!
