### ISSUE TITLE
Upgrade to be compatible with Prometheus.Client 3.0

### ISSUE THREAD

**Issue by arieradle** [PrometheusClientNet/Prometheus.Client.Owin#7]

**Comment by sanych-sun** [comment]
We will update the library soon, sorry for the delay.

**Comment by phnx47** [comment]
Released 3.0.0

**Comment by sanych-sun** [comment]
@arieradle the compatible version was released. So we close the issue.

**Comment by arieradle** [comment]
Thank you for the prompt response
